apiVersion: v1
kind: Service
metadata:
  name: {{ include "gt-helm-101.fullname" . }}
  labels:
    {{- include "gt-helm-101.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gt-helm-101.selectorLabels" . | nindent 4 }}
